---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-ems-client
  description: Buildkite Pipeline for ems-client
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/ems-client

spec:
  type: buildkite-pipeline
  owner: group:ems
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: EMS Client
      description: Pipeline to run the EMS Client tests suite on
    spec:
      repository: elastic/ems-client
      pipeline_file: ".buildkite/pipeline.yml"
      default_branch: master
      teams: # Who has access to the pipeline.
        ems: {}
        everyone:
          access_level: READ_ONLY
      provider_settings:
        publish_commit_status: true
      schedules:
        Weekly build on master branch:
          cronline: "@weekly"
          message: "Weekly tests and build"