agents:
  image: "docker.elastic.co/ci-agent-images/ems/buildkite-agent-node22:1770132294@sha256:5e84dce9a31125843aea5b7765db384c5adbb6f416120fba18c1def939365ed0"
  cpu: "2"
  memory: "2G"

steps:
  - label: ":hammer_and_wrench: Test and build"
    command: ".buildkite/build.sh"
    env:
      KIBANA_BRANCH: "main"
