agents:
  image: "docker.elastic.co/ci-agent-images/ems/buildkite-agent-node22:1763046358@sha256:468e1647968235b38473c576d963fc1581d9b2d363ef949ddfae2b5967bac9fd"
  cpu: "2"
  memory: "2G"

steps:
  - label: ":hammer_and_wrench: Test and build"
    command: ".buildkite/build.sh"
    env:
      KIBANA_BRANCH: "main"
