agents:
  image: "docker.elastic.co/ci-agent-images/ems/buildkite-agent:latest"
  memory: "1G"

steps:
  - label: ":hammer_and_wrench: Test and build"
    commands: 
      - "yarn install"
      - "yarn test"
      - "yarn build"
