agents:
  image: "docker.elastic.co/ci-agent-images/ems/uildkite-agent-node22:0.5@sha256:b14dcc6455b0678a5f76108ddabbb5c9f1455c8fc4445b03e31e7dc0f12a025d"
  cpu: "2"
  memory: "2G"

steps:
  - label: ":hammer_and_wrench: Test and build"
    command: ".buildkite/build.sh"
    env:
      KIBANA_BRANCH: "main"
