agents:
<<<<<<< HEAD
  image: "docker.elastic.co/ci-agent-images/ems/buildkite-agent-node20:0.5@sha256:01d63c1c1e9895e410a8b50c0eb0ce8e986c354085a11ed1d00355a12935ac5e"
=======
  image: "docker.elastic.co/ci-agent-images/ems/buildkite-agent-node20:0.4@sha256:709d4bf1596ca236f0f59fc30ce62a7598b544ed32c11f2869299beded97c471"
>>>>>>> 99d41b1 (chore(deps): pin dependencies (#254))
  cpu: "2"
  memory: "2G"

steps:
  - label: ":hammer_and_wrench: Test and build"
    command: ".buildkite/build.sh"
    env:
      KIBANA_BRANCH: "7.17"
