agents:
  image: "docker.elastic.co/ci-agent-images/ems/buildkite-agent-node22:1737987993@sha256:dbd0eee2a8e716034e799c08c739e03cafe769814c907a06639ca852d46bb50d"
  cpu: "2"
  memory: "2G"

steps:
  - label: ":hammer_and_wrench: Test and build"
    command: ".buildkite/build.sh"
    env:
      KIBANA_BRANCH: "main"
