agents:
  image: "docker.elastic.co/ci-agent-images/ems/buildkite-agent-node18:0.1"
  cpu: "2"
  memory: "2G"

steps:
  - label: ":hammer_and_wrench: Test and build"
    command: ".buildkite/build.sh"
