agents:
  image: "docker.elastic.co/ci-agent-images/ems/buildkite-agent-node22:1759929322@sha256:71a103e856b073aa706492dcc2aee5ca3db234e0b62487d78f577ed586405f7d"
  cpu: "2"
  memory: "2G"

steps:
  - label: ":hammer_and_wrench: Test and build"
    command: ".buildkite/build.sh"
    env:
      KIBANA_BRANCH: "main"
