agents:
  image: "docker.elastic.co/ci-agent-images/ems/buildkite-agent-node22:1764180808@sha256:5df5cf1a4429922d031d4cbfd635540d3ba3eab0f30f911079e8230880cd8c1c"
  cpu: "2"
  memory: "2G"

steps:
  - label: ":hammer_and_wrench: Test and build"
    command: ".buildkite/build.sh"
    env:
      KIBANA_BRANCH: "7.17"
