steps:
  - label: ":arrow_double_down: Install yarn"
    command: "npm install --global yarn"

  - wait: ~

  - label: ":yarn: Install dependencies"
    command: "yarn install"

  - wait: ~

  - label: ":jest: Test"
    command: "yarn test"

  - wait: ~

  - label: ":hammer_and_wrench: Build"
    command: "yarn build"
