steps:
  - label: ":hammer_and_wrench: Test and build"
    commands: 
      - "npm install --global yarn"
      - "yarn install"
      - "yarn test"
      - "yarn build"

notify:
  - slack: "#maps-ops"